language: node_js

node_js:
  - "8"

script:
  - npm test

notifications:
  email: false

dist: trusty

addons:
  apt:
    packages:
      - libsecret-1-dev
      # This is required to run new chrome on old trusty
      - libnss3

cache:
  directories:
    - node_modules
