export default test = {
  "_class": "page",
  "do_objectID": "f8fb1e10-e3f3-4093-9ff0-5593fa35e2fe",
  "exportOptions": {
    "_class": "exportOptions",
    "exportFormats": [],
    "includedLayerIds": [],
    "layerOptions": 0,
    "shouldTrim": false
  },
  "isFlippedHorizontal": false,
  "isFlippedVertical": false,
  "isLocked": false,
  "isVisible": true,
  "layerListExpandedType": 0,
  "name": "Test Page",
  "nameIsFixed": false,
  "resizingConstraint": 63,
  "resizingType": 0,
  "rotation": 0,
  "shouldBreakMaskChain": false,
  "style": {
    "_class": "style",
    "endDecorationType": 0,
    "miterLimit": 10,
    "startDecorationType": 0
  },
  "layers": [
    {
      "_class": "text",
      "do_objectID": "b6b962ed-73fc-4fd4-bda1-591435f5d3ec",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Shadow",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 24,
        "fontFamily": "Times",
        "fontWeight": 700,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 82
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 28,
        "width": 81.375,
        "x": 8,
        "y": -2123.09375
      },
      "text": "Shadow",
      "x": 8,
      "y": -2123.09375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "1921664f-2ad8-445a-81f8-154e94ac864f",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"shadow\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.5019607843137255,
              "green": 0.5019607843137255,
              "blue": 0.5019607843137255,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(128, 128, 128)",
        "boxShadow": {
          "shadowOffset": {
            "offsetX": "0",
            "offsetY": "0"
          },
          "shadowRadius": "5",
          "shadowSpread": "2",
          "shadowColor": "rgb(0, 0, 0)"
        },
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 100,
        "width": 100,
        "x": 8,
        "y": -2075.1875
      },
      "x": 8,
      "y": -2075.1875,
      "height": 100,
      "width": 100,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "b6cb0deb-6409-4e2b-8277-8cdeb7200e1d",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "box shadow",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 77
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 76.875,
        "x": 8,
        "y": -2075.1875
      },
      "text": "box shadow",
      "x": 8,
      "y": -2075.1875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "f1acb8a3-5194-4c81-830f-881b1bef1bcc",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "text shadow",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 20,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 97
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 23,
        "width": 96.09375,
        "x": 8,
        "y": -1975.1875
      },
      "text": "text shadow",
      "x": 8,
      "y": -1975.1875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "f3e96aa0-18a1-4afd-ad34-840a1bd2f002",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Image",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 24,
        "fontFamily": "Times",
        "fontWeight": 700,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 64
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 28,
        "width": 63.984375,
        "x": 8,
        "y": -1932.28125
      },
      "text": "Image",
      "x": 8,
      "y": -1932.28125,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "44590096-825e-4bd3-93af-c992ea2f2de3",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/img[@class=\"image\"]",
      "nameIsFixed": false,
      "resizingConstraint": 12,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "href": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Collage_of_Nine_Dogs.jpg",
        "display": "inline",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 263.59375,
        "width": 300,
        "x": 8,
        "y": -1884.375
      },
      "x": 8,
      "y": -1884.375,
      "height": 263.59375,
      "width": 300,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "d2bbbfbc-e9cb-41e5-a6b6-4657adc8860b",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/img[@class=\"image\"]",
      "nameIsFixed": false,
      "resizingConstraint": 12,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "href": "https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png",
        "display": "inline",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 225,
        "width": 300,
        "x": 8,
        "y": -1616.78125
      },
      "x": 8,
      "y": -1616.78125,
      "height": 225,
      "width": 300,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "a6db6e9e-a36b-44f9-977c-34281608cd42",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Border",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 24,
        "fontFamily": "Times",
        "fontWeight": 700,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 74
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 28,
        "width": 73.3125,
        "x": 8,
        "y": -1367.875
      },
      "text": "Border",
      "x": 8,
      "y": -1367.875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "91c9dfce-138b-4ffc-a4af-8da9725320ec",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"border\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(255, 0, 0)",
          "borderTopWidth": 2,
          "borderRightColor": "rgb(255, 0, 0)",
          "borderRightWidth": 2,
          "borderBottomColor": "rgb(255, 0, 0)",
          "borderBottomWidth": 2,
          "borderLeftColor": "rgb(255, 0, 0)",
          "borderLeftWidth": 2
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 104,
        "width": 104,
        "x": 8,
        "y": -1319.96875
      },
      "x": 8,
      "y": -1319.96875,
      "height": 104,
      "width": 104,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "1ca558d7-86b3-4ca7-9cc5-3b9f89625a2f",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "border",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 42
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 41.75,
        "x": 10,
        "y": -1317.96875
      },
      "text": "border",
      "x": 10,
      "y": -1317.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "e01a44f9-5171-4a20-b6f9-ee3b056cd817",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"border border1\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 255)",
          "borderTopWidth": 4,
          "borderRightColor": "rgb(0, 0, 255)",
          "borderRightWidth": 4,
          "borderBottomColor": "rgb(0, 0, 255)",
          "borderBottomWidth": 4,
          "borderLeftColor": "rgb(0, 0, 255)",
          "borderLeftWidth": 4
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 108,
        "width": 108,
        "x": 8,
        "y": -1215.96875
      },
      "x": 8,
      "y": -1215.96875,
      "height": 108,
      "width": 108,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "9e1e4b49-5502-425c-8bbd-f98fe82aeb27",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "border",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 42
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 41.75,
        "x": 12,
        "y": -1211.96875
      },
      "text": "border",
      "x": 12,
      "y": -1211.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "796136dc-4951-4f9a-a8c2-1a79304ddd7b",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"border border-radius\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "50%",
          "borderTopRightRadius": "50%",
          "borderBottomLeftRadius": "50%",
          "borderBottomRightRadius": "50%"
        },
        "border": {
          "borderTopColor": "rgb(255, 0, 0)",
          "borderTopWidth": 2,
          "borderRightColor": "rgb(255, 0, 0)",
          "borderRightWidth": 2,
          "borderBottomColor": "rgb(255, 0, 0)",
          "borderBottomWidth": 2,
          "borderLeftColor": "rgb(255, 0, 0)",
          "borderLeftWidth": 2
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 104,
        "width": 104,
        "x": 8,
        "y": -1107.96875
      },
      "x": 8,
      "y": -1107.96875,
      "height": 104,
      "width": 104,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "31b4d0e0-ca19-4f8c-b29b-bfb0495385f9",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "border radius",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 85
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 84.859375,
        "x": 10,
        "y": -1105.96875
      },
      "text": "border radius",
      "x": 10,
      "y": -1105.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "4412eb2d-6a67-4061-80e9-59b4fc066ecd",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"border border-radius2\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "10px",
          "borderTopRightRadius": "10px",
          "borderBottomLeftRadius": "10px",
          "borderBottomRightRadius": "10px"
        },
        "border": {
          "borderTopColor": "rgb(255, 0, 0)",
          "borderTopWidth": 2,
          "borderRightColor": "rgb(255, 0, 0)",
          "borderRightWidth": 2,
          "borderBottomColor": "rgb(255, 0, 0)",
          "borderBottomWidth": 2,
          "borderLeftColor": "rgb(255, 0, 0)",
          "borderLeftWidth": 2
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 104,
        "width": 104,
        "x": 8,
        "y": -1003.96875
      },
      "x": 8,
      "y": -1003.96875,
      "height": 104,
      "width": 104,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "b630dcf8-2b04-4d12-b54f-4b6ebf1343bc",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "border radius",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 85
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 84.859375,
        "x": 10,
        "y": -1001.96875
      },
      "text": "border radius",
      "x": 10,
      "y": -1001.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "f5f06631-8404-4103-abef-76353b4a4417",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Background",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 24,
        "fontFamily": "Times",
        "fontWeight": 700,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 127
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 28,
        "width": 126.28125,
        "x": 8,
        "y": -880.0625
      },
      "text": "Background",
      "x": 8,
      "y": -880.0625,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "9cc79cb5-b2f9-4f37-abcb-4bfa3b1d7528",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"bg-image\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "href": "https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png",
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 200,
        "width": 200,
        "x": 8,
        "y": -832.15625
      },
      "x": 8,
      "y": -832.15625,
      "height": 200,
      "width": 200,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "e161d01f-3b88-4411-951b-287b7dcc4724",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"bg-color\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0.5019607843137255,
              "blue": 0,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(0, 128, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 200,
        "width": 200,
        "x": 8,
        "y": -632.15625
      },
      "x": 8,
      "y": -632.15625,
      "height": 200,
      "width": 200,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "4faafdf1-f39c-4c51-8513-c6f2e1f8cc1d",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"bg-gradient\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          },
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "alpha": 1,
              "blue": 0.847,
              "green": 0.847,
              "red": 0.847
            },
            "fillType": 1,
            "gradient": {
              "_class": "gradient",
              "elipseLength": 0,
              "from": "{0.5, 0",
              "gradientType": 0,
              "shouldSmoothenOpacity": false,
              "stops": [
                {
                  "_class": "gradientStop",
                  "color": {
                    "_class": "color",
                    "red": 1,
                    "green": 0,
                    "blue": 0,
                    "alpha": 1
                  },
                  "position": 0
                },
                {
                  "_class": "gradientStop",
                  "color": {
                    "_class": "color",
                    "red": 1,
                    "green": 1,
                    "blue": 0,
                    "alpha": 1
                  },
                  "position": 1
                }
              ],
              "to": "{0.5, 1}"
            },
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 200,
        "width": 200,
        "x": 8,
        "y": -432.15625
      },
      "x": 8,
      "y": -432.15625,
      "height": 200,
      "width": 200,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "1aee86e7-4ff5-4249-a326-8ead9a89b721",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Font",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 24,
        "fontFamily": "Times",
        "fontWeight": 700,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 48
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 28,
        "width": 48,
        "x": 8,
        "y": -212.25
      },
      "text": "Font",
      "x": 8,
      "y": -212.25,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "64007652-b9ed-45af-885a-147a76bb5c15",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Font one",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(255, 0, 0)",
        "fontSize": 16,
        "fontFamily": "CourierNew",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 57
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 56.4375,
        "x": 8,
        "y": -164.34375
      },
      "text": "Font one",
      "x": 8,
      "y": -164.34375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "90957dbb-8b24-4ed5-a64d-422298639242",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Font two",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 128, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "letterSpacing": 20,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 218
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 217.34375,
        "x": 8,
        "y": -130.34375
      },
      "text": "Font two",
      "x": 8,
      "y": -130.34375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "d7bd970b-6f24-436b-b8b6-a44785bc4719",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Font three",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 255)",
        "fontSize": 30,
        "fontFamily": "Times",
        "fontWeight": 400,
        "lineHeight": 40,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 123
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 36,
        "width": 122.46875,
        "x": 8,
        "y": -82.34375
      },
      "text": "Font three",
      "x": 8,
      "y": -82.34375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "8c80c208-4e2f-4ae1-a5c0-4a6a03b7640d",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Font four",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "uppercase",
        "textDecoration": "none",
        "textAlign": "center",
        "width": 89
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 88.453125,
        "x": 186.265625,
        "y": -12.34375
      },
      "text": "Font four",
      "x": 186.265625,
      "y": -12.34375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "1013f4ad-7e46-487d-ad10-3d8186d428c2",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Font five",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "underline",
        "textAlign": "start",
        "width": 58
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 57.34375,
        "x": 8,
        "y": 21.65625
      },
      "text": "Font five",
      "x": 8,
      "y": 21.65625,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "97a54ed6-a044-43ed-8c99-2751ae5085a5",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Font six",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "line-through",
        "textAlign": "start",
        "width": 53
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 52.015625,
        "x": 8,
        "y": 55.65625
      },
      "text": "Font six",
      "x": 8,
      "y": 55.65625,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "696fcd57-9acd-4b5c-8d87-8bc7575ac719",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Font seven",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "right",
        "width": 70
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 69.765625,
        "x": 383.234375,
        "y": 89.65625
      },
      "text": "Font seven",
      "x": 383.234375,
      "y": 89.65625,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "7fa53619-d2ef-4b26-9b91-0c9d63088485",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Visibility",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 24,
        "fontFamily": "Times",
        "fontWeight": 700,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 93
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 28,
        "width": 92.46875,
        "x": 8,
        "y": 127.5625
      },
      "text": "Visibility",
      "x": 8,
      "y": 127.5625,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "1d122bf6-9ad6-431b-8a37-4c5e68a00f8d",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"box\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 1,
              "green": 0,
              "blue": 0,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(255, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 100,
        "width": 100,
        "x": 8,
        "y": 275.46875
      },
      "x": 8,
      "y": 275.46875,
      "height": 100,
      "width": 100,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "c2017b4b-1b8f-464d-b182-ee875c93d489",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "block",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 36
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 35.546875,
        "x": 8,
        "y": 275.46875
      },
      "text": "block",
      "x": 8,
      "y": 275.46875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "b83fe63a-735a-4deb-bc76-397250e9f402",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"box\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 1,
              "green": 0,
              "blue": 0,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "inline-block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(255, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 100,
        "width": 100,
        "x": 8,
        "y": 375.46875
      },
      "x": 8,
      "y": 375.46875,
      "height": 100,
      "width": 100,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "a5084142-e1a5-4d55-bbc5-04f070308642",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "inline-block",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 78
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 77.3125,
        "x": 8,
        "y": 375.46875
      },
      "text": "inline-block",
      "x": 8,
      "y": 375.46875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "25ab0de5-1bdd-42ee-ae53-562f16e153bb",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"box\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 1,
              "green": 0,
              "blue": 0,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "inline-block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(255, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 100,
        "width": 100,
        "x": 112,
        "y": 375.46875
      },
      "x": 112,
      "y": 375.46875,
      "height": 100,
      "width": 100,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "c839d027-2e8a-4084-8de1-b2a41fe927ac",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "inline-block",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 78
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 77.3125,
        "x": 112,
        "y": 375.46875
      },
      "text": "inline-block",
      "x": 112,
      "y": 375.46875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "a43c5d50-bfbc-4797-941f-3f96610dd18c",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Opacity",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 24,
        "fontFamily": "Times",
        "fontWeight": 700,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 82
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 28,
        "width": 81.328125,
        "x": 8,
        "y": 495.375
      },
      "text": "Opacity",
      "x": 8,
      "y": 495.375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "b78ea4ba-0fa2-4823-abf4-0d468e281d5a",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"box\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 1,
              "green": 0,
              "blue": 0,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "0.8"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(255, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 100,
        "width": 100,
        "x": 8,
        "y": 543.28125
      },
      "x": 8,
      "y": 543.28125,
      "height": 100,
      "width": 100,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "e8db2202-7195-49f1-bf9f-9734ed6b2227",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "opacity 0.8",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 72
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 71.09375,
        "x": 8,
        "y": 543.28125
      },
      "text": "opacity 0.8",
      "x": 8,
      "y": 543.28125,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "c48ce153-278c-40df-adc0-642d6cf87f78",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "/html[1]/body[1]/div[@class=\"box\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 1,
              "green": 0,
              "blue": 0,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "0.3"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(255, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 100,
        "width": 100,
        "x": 8,
        "y": 643.28125
      },
      "x": 8,
      "y": 643.28125,
      "height": 100,
      "width": 100,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "05ca5b4c-6978-4803-8f39-eef549bf5f8e",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "opacity 0.3",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(0, 0, 0)",
        "fontSize": 16,
        "fontFamily": "Times",
        "fontWeight": 400,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "start",
        "width": 72
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 18,
        "width": 71.09375,
        "x": 8,
        "y": 643.28125
      },
      "text": "opacity 0.3",
      "x": 8,
      "y": 643.28125,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    }
  ],
  "frame": {
    "_class": "rect",
    "constrainProportions": false,
    "height": 445,
    "width": 2866,
    "x": 0,
    "y": 0
  },
  "horizontalRulerData": {
    "_class": "rulerData",
    "base": 0,
    "guides": []
  },
  "verticalRulerData": {
    "_class": "rulerData",
    "base": 0,
    "guides": []
  },
  "hasClickThrough": true,
  "includeInCloudUpload": true
}
;
