export default test = {
  "_class": "page",
  "do_objectID": "42aa58e2-85ab-497c-8bad-9e12b6c0ddf4",
  "exportOptions": {
    "_class": "exportOptions",
    "exportFormats": [],
    "includedLayerIds": [],
    "layerOptions": 0,
    "shouldTrim": false
  },
  "isFlippedHorizontal": false,
  "isFlippedVertical": false,
  "isLocked": false,
  "isVisible": true,
  "layerListExpandedType": 0,
  "name": "Test Page",
  "nameIsFixed": false,
  "resizingConstraint": 63,
  "resizingType": 0,
  "rotation": 0,
  "shouldBreakMaskChain": false,
  "style": {
    "_class": "style",
    "endDecorationType": 0,
    "miterLimit": 10,
    "startDecorationType": 0
  },
  "layers": [
    {
      "_class": "text",
      "do_objectID": "6aff5ee4-3227-4b4f-ae69-ac54531845b1",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "⇶",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(165, 165, 165)",
        "fontSize": 16,
        "fontFamily": "ddg-serp-icons",
        "fontWeight": 400,
        "lineHeight": 34,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "center",
        "width": 16
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 16,
        "x": 597,
        "y": 23
      },
      "text": "⇶",
      "x": 597,
      "y": 23,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "3dee43cb-5f3a-409c-bb96-822ef3e401fa",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"logo_homepage_link\")",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "href": "https://duckduckgo.com/assets/logo_homepage.normal.v107.svg",
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgba(0, 0, 0, 0)",
          "borderTopWidth": 0,
          "borderRightColor": "rgba(0, 0, 0, 0)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgba(0, 0, 0, 0)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgba(0, 0, 0, 0)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 200,
        "width": 250,
        "x": 189,
        "y": 180.234375
      },
      "x": 189,
      "y": 180.234375,
      "height": 200,
      "width": 250,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "64f9b517-08b4-461b-952c-f121310babac",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "About DuckDuckGo",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgba(0, 0, 0, 0)",
        "fontSize": 0,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 0,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "center",
        "width": 0
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 0,
        "width": 0,
        "x": -4685.5,
        "y": 180.234375
      },
      "text": "About DuckDuckGo",
      "x": -4685.5,
      "y": 180.234375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "6ee22d60-63fc-48c6-bca7-c746f4a3907b",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"search_form_homepage\")",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 1,
              "green": 1,
              "blue": 1,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(255, 255, 255)",
        "boxShadow": {
          "shadowOffset": {
            "offsetX": "0",
            "offsetY": "2"
          },
          "shadowRadius": "3",
          "shadowSpread": "0",
          "shadowColor": "rgba(0, 0, 0, 0.06)"
        },
        "borderRadius": {
          "borderTopLeftRadius": "3px",
          "borderTopRightRadius": "3px",
          "borderBottomLeftRadius": "3px",
          "borderBottomRightRadius": "3px"
        },
        "border": {
          "borderTopColor": "rgba(0, 0, 0, 0.15)",
          "borderTopWidth": 1,
          "borderRightColor": "rgba(0, 0, 0, 0.15)",
          "borderRightWidth": 1,
          "borderBottomColor": "rgba(0, 0, 0, 0.15)",
          "borderBottomWidth": 1,
          "borderLeftColor": "rgba(0, 0, 0, 0.15)",
          "borderLeftWidth": 1
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 45.953125,
        "width": 429.796875,
        "x": 99.09375,
        "y": 410.46875
      },
      "x": 99.09375,
      "y": 410.46875,
      "height": 45.953125,
      "width": 429.796875,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "3a012196-116c-411e-875e-21214879b15d",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "The search engine that doesn't track you.",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(154, 154, 154)",
        "fontSize": 18,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 25,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "center",
        "width": 326
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 21,
        "width": 325.34375,
        "x": 102.015625,
        "y": 479.8125
      },
      "text": "The search engine that doesn't track you.",
      "x": 102.015625,
      "y": 479.8125,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "79406a8b-6cb7-4a62-b458-8efe8aa95edd",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": ".",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(154, 154, 154)",
        "fontSize": 18,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 25,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "center",
        "width": 5
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 21,
        "width": 4.125,
        "x": 521.84375,
        "y": 479.8125
      },
      "text": ".",
      "x": 521.84375,
      "y": 479.8125,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "7b5ed417-7b2b-4f32-a174-f725ac96a90f",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Learn More",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(58, 127, 180)",
        "fontSize": 18,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 25,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "center",
        "width": 90
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 21,
        "width": 89.84375,
        "x": 432,
        "y": 479.8125
      },
      "text": "Learn More",
      "x": 432,
      "y": 479.8125,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "80998a29-e3e8-43ff-9ee6-a3108a295e52",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.9490196078431372,
              "green": 0.9490196078431372,
              "blue": 0.9490196078431372,
              "alpha": 0.9764705882352941
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(242, 242, 242, 0.976)",
        "boxShadow": {
          "shadowOffset": {
            "offsetX": "-1",
            "offsetY": "0"
          },
          "shadowRadius": "1",
          "shadowSpread": "0",
          "shadowColor": "rgba(0, 0, 0, 0.2)"
        },
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 826,
        "width": 201.59375,
        "x": 631.6062622070312,
        "y": 0
      },
      "x": 631.6062622070312,
      "y": 0,
      "height": 826,
      "width": 201.59375,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "464d309f-4a2a-4916-9470-7da8c67c41b7",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "X",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(191, 191, 191)",
        "fontSize": 17,
        "fontFamily": "ddg-serp-icons",
        "fontWeight": 400,
        "lineHeight": 17,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "center",
        "width": 18
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 17,
        "width": 17.265625,
        "x": 798.6531372070312,
        "y": 27.640625
      },
      "text": "X",
      "x": 798.6531372070312,
      "y": 27.640625,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "6521c38d-3e27-41b6-bb8a-b4af651b92b0",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Settings",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(136, 136, 136)",
        "fontSize": 10,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 17,
        "textTransform": "uppercase",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 49
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 13,
        "width": 48.984375,
        "x": 653.2000122070312,
        "y": 29.203125
      },
      "text": "Settings",
      "x": 653.2000122070312,
      "y": 29.203125,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "a2ab9e18-0fca-4cdf-b111-e6d27c005f19",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]/ul[@class=\"nav-menu__list\"]/ul[@class=\"nav-menu--theme\"]/li[@class=\"nav-menu__item\"]/ul[@class=\"nav-menu__themes\"]/li[@class=\"nav-menu__theme  js-side-menu-theme theme-is-selected\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0,
              "green": 0,
              "blue": 0,
              "alpha": 0
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgba(0, 0, 0, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "13px",
          "borderTopRightRadius": "13px",
          "borderBottomLeftRadius": "13px",
          "borderBottomRightRadius": "13px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 1,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 1,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 1,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 1
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 24,
        "width": 24,
        "x": 653.2000122070312,
        "y": 59.828125
      },
      "x": 653.2000122070312,
      "y": 59.828125,
      "height": 24,
      "width": 24,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "5ebfea6b-4f45-4c99-bd9c-b16c3c52fbb4",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]/ul[@class=\"nav-menu__list\"]/ul[@class=\"nav-menu--theme\"]/li[@class=\"nav-menu__item\"]/ul[@class=\"nav-menu__themes\"]/li[@class=\"nav-menu__theme  js-side-menu-theme theme-is-selected\"]/span[@class=\"nav-menu__theme-color\"]/span[@class=\"nav-menu__theme-color-top\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.03137254901960784,
              "green": 0.28627450980392155,
              "blue": 0.6,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(8, 73, 153)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 25.455841064453125,
        "width": 25.455810546875,
        "x": 647.4721069335938,
        "y": 54.10020446777344
      },
      "x": 647.4721069335938,
      "y": 54.10020446777344,
      "height": 25.455841064453125,
      "width": 25.455810546875,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "b0fcc380-1bd3-4b44-8f5e-5db8b9905d17",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]/ul[@class=\"nav-menu__list\"]/ul[@class=\"nav-menu--theme\"]/li[@class=\"nav-menu__item\"]/ul[@class=\"nav-menu__themes\"]/li[@class=\"nav-menu__theme  js-side-menu-theme theme-is-selected\"]/span[@class=\"nav-menu__theme-color\"]/span[@class=\"nav-menu__theme-color-bot\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.5333333333333333,
              "green": 0.5333333333333333,
              "blue": 0.5333333333333333,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(136, 136, 136)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 25.455841064453125,
        "width": 25.455810546875,
        "x": 658.4721069335938,
        "y": 65.10020446777344
      },
      "x": 658.4721069335938,
      "y": 65.10020446777344,
      "height": 25.455841064453125,
      "width": 25.455810546875,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "9855a53c-0e8c-4e9b-94a4-28852d72bab9",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]/ul[@class=\"nav-menu__list\"]/ul[@class=\"nav-menu--theme\"]/li[@class=\"nav-menu__item\"]/ul[@class=\"nav-menu__themes\"]/li[@class=\"nav-menu__theme  js-side-menu-theme\"]/span[@class=\"nav-menu__theme-color\"]/span[@class=\"nav-menu__theme-color-top\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.2,
              "green": 0.2,
              "blue": 0.2,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(51, 51, 51)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 25.455841064453125,
        "width": 25.455810546875,
        "x": 676.4721069335938,
        "y": 54.10020446777344
      },
      "x": 676.4721069335938,
      "y": 54.10020446777344,
      "height": 25.455841064453125,
      "width": 25.455810546875,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "c51f35d4-58d0-4a46-bfb3-102e4d894c22",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]/ul[@class=\"nav-menu__list\"]/ul[@class=\"nav-menu--theme\"]/li[@class=\"nav-menu__item\"]/ul[@class=\"nav-menu__themes\"]/li[@class=\"nav-menu__theme  js-side-menu-theme\"]/span[@class=\"nav-menu__theme-color\"]/span[@class=\"nav-menu__theme-color-bot\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.5333333333333333,
              "green": 0.5333333333333333,
              "blue": 0.5333333333333333,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(136, 136, 136)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 25.455841064453125,
        "width": 25.455810546875,
        "x": 687.4721069335938,
        "y": 65.10020446777344
      },
      "x": 687.4721069335938,
      "y": 65.10020446777344,
      "height": 25.455841064453125,
      "width": 25.455810546875,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "dd50d295-cd14-493d-95ca-60e312d78f1d",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]/ul[@class=\"nav-menu__list\"]/ul[@class=\"nav-menu--theme\"]/li[@class=\"nav-menu__item\"]/ul[@class=\"nav-menu__themes\"]/li[@class=\"nav-menu__theme  js-side-menu-theme\"]/span[@class=\"nav-menu__theme-color\"]/span[@class=\"nav-menu__theme-color-top\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.20392156862745098,
              "green": 0.20392156862745098,
              "blue": 0.8313725490196079,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(52, 52, 212)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 25.455841064453125,
        "width": 25.455810546875,
        "x": 705.4721069335938,
        "y": 54.10020446777344
      },
      "x": 705.4721069335938,
      "y": 54.10020446777344,
      "height": 25.455841064453125,
      "width": 25.455810546875,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "05902d40-8762-405a-b7d0-8f9c3e95c5db",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]/ul[@class=\"nav-menu__list\"]/ul[@class=\"nav-menu--theme\"]/li[@class=\"nav-menu__item\"]/ul[@class=\"nav-menu__themes\"]/li[@class=\"nav-menu__theme  js-side-menu-theme\"]/span[@class=\"nav-menu__theme-color\"]/span[@class=\"nav-menu__theme-color-bot\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.01568627450980392,
              "green": 0.49019607843137253,
              "blue": 0,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(4, 125, 0)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 25.455841064453125,
        "width": 25.455810546875,
        "x": 716.4721069335938,
        "y": 65.10020446777344
      },
      "x": 716.4721069335938,
      "y": 65.10020446777344,
      "height": 25.455841064453125,
      "width": 25.455810546875,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "c1a90444-1257-4b79-a589-948a3cb9fa6f",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]/ul[@class=\"nav-menu__list\"]/ul[@class=\"nav-menu--theme\"]/li[@class=\"nav-menu__item\"]/ul[@class=\"nav-menu__themes\"]/li[@class=\"nav-menu__theme  js-side-menu-theme\"]/span[@class=\"nav-menu__theme-color\"]/span[@class=\"nav-menu__theme-color-top\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.26666666666666666,
              "green": 0.26666666666666666,
              "blue": 0.26666666666666666,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(68, 68, 68)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 25.455841064453125,
        "width": 25.455810546875,
        "x": 734.4721069335938,
        "y": 54.10020446777344
      },
      "x": 734.4721069335938,
      "y": 54.10020446777344,
      "height": 25.455841064453125,
      "width": 25.455810546875,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "shapeGroup",
      "do_objectID": "36b038eb-a892-49cf-9693-da189d416d94",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "id(\"pg-index\")/div[@class=\"site-wrapper  site-wrapper--home  js-site-wrapper\"]/div[@class=\"nav-menu--slideout\"]/ul[@class=\"nav-menu__list\"]/ul[@class=\"nav-menu--theme\"]/li[@class=\"nav-menu__item\"]/ul[@class=\"nav-menu__themes\"]/li[@class=\"nav-menu__theme  js-side-menu-theme\"]/span[@class=\"nav-menu__theme-color\"]/span[@class=\"nav-menu__theme-color-bot\"]",
      "nameIsFixed": false,
      "resizingConstraint": 63,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "_class": "style",
        "fills": [
          {
            "_class": "fill",
            "isEnabled": true,
            "color": {
              "_class": "color",
              "red": 0.13333333333333333,
              "green": 0.13333333333333333,
              "blue": 0.13333333333333333,
              "alpha": 1
            },
            "fillType": 0,
            "noiseIndex": 0,
            "noiseIntensity": 0,
            "patternFillType": 1,
            "patternTileScale": 1
          }
        ],
        "borders": [],
        "shadows": [],
        "innerShadows": [],
        "endDecorationType": 0,
        "miterLimit": 10,
        "startDecorationType": 0,
        "contextSettings": {
          "_class": "graphicsContextSettings",
          "blendMode": 0,
          "opacity": "1"
        },
        "display": "block",
        "alignItems": "normal",
        "justifyContent": "normal",
        "backgroundColor": "rgb(34, 34, 34)",
        "borderRadius": {
          "borderTopLeftRadius": "0px",
          "borderTopRightRadius": "0px",
          "borderBottomLeftRadius": "0px",
          "borderBottomRightRadius": "0px"
        },
        "border": {
          "borderTopColor": "rgb(51, 51, 51)",
          "borderTopWidth": 0,
          "borderRightColor": "rgb(51, 51, 51)",
          "borderRightWidth": 0,
          "borderBottomColor": "rgb(51, 51, 51)",
          "borderBottomWidth": 0,
          "borderLeftColor": "rgb(51, 51, 51)",
          "borderLeftWidth": 0
        }
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 25.455841064453125,
        "width": 25.455810546875,
        "x": 745.4721069335938,
        "y": 65.10020446777344
      },
      "x": 745.4721069335938,
      "y": 65.10020446777344,
      "height": 25.455841064453125,
      "width": 25.455810546875,
      "hasClickThrough": false,
      "clippingMaskMode": 0,
      "hasClippingMask": false,
      "windingRule": 1
    },
    {
      "_class": "text",
      "do_objectID": "0daf97c9-1124-478f-8afb-a525af26ef06",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "More Themes",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 80
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 79.953125,
        "x": 653.2000122070312,
        "y": 94.265625
      },
      "text": "More Themes",
      "x": 653.2000122070312,
      "y": 94.265625,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "2869e5db-3be8-4b30-aebe-231e4994100a",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Other Settings",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 84
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 83.40625,
        "x": 653.2000122070312,
        "y": 115.265625
      },
      "text": "Other Settings",
      "x": 653.2000122070312,
      "y": 115.265625,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "d72e0de0-1bd7-46ce-bb03-a23272f64fad",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Menu",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(136, 136, 136)",
        "fontSize": 10,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 17,
        "textTransform": "uppercase",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 31
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 13,
        "width": 30.046875,
        "x": 653.2000122070312,
        "y": 171.90625
      },
      "text": "Menu",
      "x": 653.2000122070312,
      "y": 171.90625,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "7cdeb491-3538-4129-b68f-c1d79bd54582",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "About",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 35
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 35,
        "x": 653.2000122070312,
        "y": 195.96875
      },
      "text": "About",
      "x": 653.2000122070312,
      "y": 195.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "4d4d785a-61e4-4dc5-9ca4-f121ebe18a22",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "App",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 24
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 23.796875,
        "x": 653.2000122070312,
        "y": 216.96875
      },
      "text": "App",
      "x": 653.2000122070312,
      "y": 216.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "5171b650-da4b-4c19-bc7d-b528bfb0d56f",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Bangs",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 37
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 36.265625,
        "x": 653.2000122070312,
        "y": 237.96875
      },
      "text": "Bangs",
      "x": 653.2000122070312,
      "y": 237.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "9b69d244-e965-4bca-82c0-e22425ffb590",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Spread",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 42
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 41.640625,
        "x": 653.2000122070312,
        "y": 258.96875
      },
      "text": "Spread",
      "x": 653.2000122070312,
      "y": 258.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "1ed42327-aad9-484e-96cb-6f22a51a1945",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Careers",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 46
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 45.625,
        "x": 653.2000122070312,
        "y": 279.96875
      },
      "text": "Careers",
      "x": 653.2000122070312,
      "y": 279.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "b447b578-3bb8-4d44-bf75-acd17708db70",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Press",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 32
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 31.828125,
        "x": 653.2000122070312,
        "y": 300.96875
      },
      "text": "Press",
      "x": 653.2000122070312,
      "y": 300.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "1d34c0eb-888c-406e-8f60-cb87dee8e1ab",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Help",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 28
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 27.359375,
        "x": 653.2000122070312,
        "y": 321.96875
      },
      "text": "Help",
      "x": 653.2000122070312,
      "y": 321.96875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "9f553425-3314-45bf-8504-e03e1c103578",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Privacy",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(136, 136, 136)",
        "fontSize": 10,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 17,
        "textTransform": "uppercase",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 43
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 13,
        "width": 42.5625,
        "x": 653.2000122070312,
        "y": 378.609375
      },
      "text": "Privacy",
      "x": 653.2000122070312,
      "y": 378.609375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "a82deeac-79f6-4399-9552-c8186e8f384e",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Blog",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 27
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 26.40625,
        "x": 653.2000122070312,
        "y": 402.671875
      },
      "text": "Blog",
      "x": 653.2000122070312,
      "y": 402.671875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "3b4585f0-8f7a-4fa5-acb1-d37ba272ba85",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "DontTrack.us",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 75
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 74.78125,
        "x": 653.2000122070312,
        "y": 423.671875
      },
      "text": "DontTrack.us",
      "x": 653.2000122070312,
      "y": 423.671875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "583e2ef3-8748-46c8-b1a3-948a3aa0b09a",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Policy",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 35
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 34.09375,
        "x": 653.2000122070312,
        "y": 444.671875
      },
      "text": "Policy",
      "x": 653.2000122070312,
      "y": 444.671875,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "7fb0f3e9-df45-4ed8-9e5a-f0fb8cb243de",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Keep in Touch",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(136, 136, 136)",
        "fontSize": 10,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 17,
        "textTransform": "uppercase",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 78
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 13,
        "width": 77.515625,
        "x": 653.2000122070312,
        "y": 501.3125
      },
      "text": "Keep in Touch",
      "x": 653.2000122070312,
      "y": 501.3125,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "3593b03d-5d23-4b47-978d-327473f11865",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Twitter",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 40
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 39.015625,
        "x": 653.2000122070312,
        "y": 525.375
      },
      "text": "Twitter",
      "x": 653.2000122070312,
      "y": 525.375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    },
    {
      "_class": "text",
      "do_objectID": "4af6c660-37c6-41f2-b048-5a7de75d337b",
      "exportOptions": {
        "_class": "exportOptions",
        "exportFormats": [],
        "includedLayerIds": [],
        "layerOptions": 0,
        "shouldTrim": false
      },
      "isFlippedHorizontal": false,
      "isFlippedVertical": false,
      "isLocked": false,
      "isVisible": true,
      "layerListExpandedType": 0,
      "name": "Reddit",
      "nameIsFixed": false,
      "resizingConstraint": 47,
      "resizingType": 0,
      "rotation": 0,
      "shouldBreakMaskChain": false,
      "style": {
        "color": "rgb(51, 51, 51)",
        "fontSize": 13,
        "fontFamily": "Proxima Nova",
        "fontWeight": 400,
        "lineHeight": 21,
        "textTransform": "none",
        "textDecoration": "none",
        "textAlign": "left",
        "width": 38
      },
      "layers": [],
      "frame": {
        "_class": "rect",
        "constrainProportions": false,
        "height": 16,
        "width": 37.109375,
        "x": 653.2000122070312,
        "y": 546.375
      },
      "text": "Reddit",
      "x": 653.2000122070312,
      "y": 546.375,
      "automaticallyDrawOnUnderlyingPath": false,
      "dontSynchroniseWithSymbol": false,
      "glyphBounds": "",
      "heightIsClipped": false,
      "lineSpacingBehaviour": 2,
      "textBehaviour": 0
    }
  ],
  "frame": {
    "_class": "rect",
    "constrainProportions": false,
    "height": 628,
    "width": 826,
    "x": 0,
    "y": 0
  },
  "horizontalRulerData": {
    "_class": "rulerData",
    "base": 0,
    "guides": []
  },
  "verticalRulerData": {
    "_class": "rulerData",
    "base": 0,
    "guides": []
  },
  "hasClickThrough": true,
  "includeInCloudUpload": true
}
;
